name: 🚀 Release Docs

on:
    push:
        tags:
            - '*'
    workflow_dispatch:

jobs:
    publish:
        name: 🚀 Build and release docs
        runs-on: ubuntu-latest
        permissions:
            contents: read
            deployments: write
        steps:
            -   name: 👀 Checkout
                uses: actions/checkout@v7

            -   name: ⚙️ Setup Bun
                uses: oven-sh/setup-bun@v2

            -   name: 📦️ Install dependencies
                run: bun install --frozen-lockfile

            -   name: 🔨 Build Docs
                run: bun run docs:build

            -   name: 🚀 Deploy Docs
                id: deploy
                uses: cloudflare/wrangler-action@v3
                with:
                    accountId: 5e565cf9fa55b0eae1f8131903da2ca9
                    apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                    gitHubToken: ${{ secrets.GITHUB_TOKEN }}
                    wranglerVersion: "4.108.0"

            -   name: ⭐️ Output
                run: |
                    echo "Deployed on ${{ steps.deploy.outputs.deployment-url }}"
